CREATE DATABASE INTERVIEW_QUES;
USE INTERVIEW_QUES;

CREATE TABLE AG_ACTIVITY(
USERNAME VARCHAR(20) NOT NULL,
ACTIVITY VARCHAR(30) NOT NULL,
STARTDATE DATE NOT NULL,
ENDDATE DATE NOT NULL);

INSERT INTO AG_ACTIVITY(USERNAME,ACTIVITY,STARTDATE,ENDDATE) VALUES ('AMY','TRAVEL','2020-02-12','2020-02-20');
INSERT INTO AG_ACTIVITY(USERNAME,ACTIVITY,STARTDATE,ENDDATE) VALUES ('AMY','DANCING','2020-02-21','2020-02-23');
INSERT INTO AG_ACTIVITY(USERNAME,ACTIVITY,STARTDATE,ENDDATE) VALUES ('AMY','TRAVEL','2020-02-24','2020-02-28');
INSERT INTO AG_ACTIVITY(USERNAME,ACTIVITY,STARTDATE,ENDDATE) VALUES ('JOE','TRAVEL','2020-02-11','2020-02-18');
INSERT INTO AG_ACTIVITY(USERNAME,ACTIVITY,STARTDATE,ENDDATE) VALUES ('ADAM','TRAVEL','2020-02-12','2020-02-20');
INSERT INTO AG_ACTIVITY(USERNAME,ACTIVITY,STARTDATE,ENDDATE) VALUES ('ADAM','DANCING','2020-02-21','2020-02-23');
INSERT INTO AG_ACTIVITY(USERNAME,ACTIVITY,STARTDATE,ENDDATE) VALUES ('ADAM','SINGING','2020-02-24','2020-02-28');
INSERT INTO AG_ACTIVITY(USERNAME,ACTIVITY,STARTDATE,ENDDATE) VALUES ('ADAM','TRAVEL','2020-02-01','2020-03-28');


SELECT * FROM AG_ACTIVITY;

/* Solution */

WITH CTE AS
(SELECT *,
ROW_NUMBER() OVER(PARTITION BY USERNAME ORDER BY STARTDATE) AS RN,
COUNT(*) OVER(PARTITION BY USERNAME ORDER BY STARTDATE
             RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS CNT            
FROM AG_ACTIVITY)

SELECT USERNAME,ACTIVITY,STARTDATE,ENDDATE
FROM CTE 
WHERE RN =CASE WHEN CNT=1 THEN 1 ELSE CNT -1 END;